language: php

php:
  - 7.1

before_script:
  - echo ${TRAVIS_PHP_VERSION:0:3}
  - cd ..
  - git clone git://github.com/uthando-cms/uthando.git
  - cd uthando
  - composer install
  - cp -R ../uthando-common ./vendor/uthando-cms/uthando-common
  - cd ./vendor/uthando-cms/uthando-common/test

script:
  - phpdbg -qrr ../../../bin/phpunit -v

after_script:
  - cd ../../../
  - php bin/test-reporter --coverage-report=build/logs/clover.xml
