language: php

php:
  - 7.0

before_script:
  - cd ..
  - git clone git://github.com/uthando-cms/uthando.git
  - cp -R ./uthando-common/test/composer.test.json ./uthando/composer.json
  - cd uthando
  - composer install
  - cp -R ../uthando-common ./module/UthandoCommon
  - cd module/UthandoCommon/test

script:
  - phpdbg -qrr ../../../vendor/bin/phpunit -v

after_script:
  - cd ../
  - cp -R ../../vendor ./vendor
  - php vendor/bin/test-reporter --coverage-report=build/logs/clover.xml

