language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - echo ${TRAVIS_PHP_VERSION:0:3}
  - cd ..
  - git clone git://github.com/uthando-cms/uthando.git
  - cd uthando
  - composer install
  - cp -R ../uthando-common ./module/UthandoCommon
  - cd module/UthandoCommon/test

script:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then phpdbg -qrr ../../../vendor/bin/phpunit -v; fi

after_script:
  - cd ../
  - cp -R ../../vendor ./vendor
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then php vendor/bin/test-reporter --coverage-report=build/logs/clover.xml; fi

matrix:
  allow_failures:
    - php: hhvm

