language: php

php:
  - 7.0
  - hhvm

before_script:
  - cd ..
  - git clone git://github.com/uthando-cms/uthando.git
  - cd uthando
  - composer install
  - cp -R ../uthando-common ./module/UthandoCommon
  - cd module/UthandoCommon/test

script:
  - phpunit

after_script:
  - cd ../
  - php vendor/bin/test-reporter --coverage-report=build/logs/clover.xml

matrix:
  allow_failures:
    - php: hhvm
