<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'application/partial/pager'              => __DIR__ . '/view/application/partial/pager.phtml',
    'application/partial/paginate'           => __DIR__ . '/view/application/partial/paginate.phtml',
    'error/404'                              => __DIR__ . '/view/error/404.phtml',
    'error/index'                            => __DIR__ . '/view/error/index.phtml',
    'layout/xml-http-request-error'          => __DIR__ . '/view/layout/xml-http-request-error.phtml',
    'uthando-common/partial/tb-flashmessage' => __DIR__ . '/view/uthando-common/partial/tb-flashmessage.phtml',
);
