<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'error/404'                     => __DIR__ . '/view/error/404.phtml',
    'error/index'                   => __DIR__ . '/view/error/index.phtml',
    'layout/xml-http-request-error' => __DIR__ . '/view/layout/xml-http-request-error.phtml',
    'partial/pager'                 => __DIR__ . '/view/partial/pager.phtml',
    'partial/paginate'              => __DIR__ . '/view/partial/paginate.phtml',
    'partial/tb-flashmessage'       => __DIR__ . '/view/partial/tb-flashmessage.phtml',
);
